//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostComment
    {
        public long ID { get; set; }
        public long PostID { get; set; }
        public string Comment { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long ParentCommentID { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
    }
}
