//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMessage
    {
        public long ForumMessageId { get; set; }
        public string MessageDescription { get; set; }
        public Nullable<long> ForumId { get; set; }
        public Nullable<bool> IsCorrectAnswer { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Forum Forum { get; set; }
    }
}
